spotless.googleJavaFormat=${version.spotless.google-java-format}
spotless.lib=${version.spotless-lib}
slf4j.api=${version.slf4j}
guava=${version.guava}
dom4j=${version.dom4j}
sortpom=${version.sortpom}
flexmark=${version.flexmark}

